id: P004513
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159386
  title: བོད་ལྗོངས་སྨན་རྩིས་ཁང་གི་ལོ་ཐོ།（༢༠༡༣）
  author: ''
  volumes:
    ca11d5ec425f4550966d663eea591e81:
      image_group_id: I4PD4388
      title: ''
      volume_number: 1
      total_pages: 222
